"""empty message

Revision ID: 1787daf3c7a1
Revises: 
Create Date: 2018-12-07 01:32:26.037744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1787daf3c7a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('json_body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('db_flags', sqlalchemy_json.MutableJson(), nullable=True),
    sa.Column('totp_key', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('handle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('acct', sa.Text(), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('external_json_cache', sa.Text(), nullable=True),
    sa.Column('external_json_fetched', sa.DateTime(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('banner_url', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=True),
    sa.Column('follow_confirm', sa.Boolean(), nullable=True),
    sa.Column('autoconfirm_mutual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.Column('actor', sa.Text(), nullable=True),
    sa.Column('to', sqlalchemy_json.MutableJson(), nullable=True),
    sa.Column('cc', sqlalchemy_json.MutableJson(), nullable=True),
    sa.Column('handle_box', sa.Text(), nullable=False),
    sa.Column('content_uri', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Enum('Create', 'Announce', 'Like', 'Flag', 'Follow'), nullable=True),
    sa.ForeignKeyConstraint(['handle_box'], ['handle.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('following_handle', sa.Integer(), nullable=True),
    sa.Column('followed', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['followed'], ['handle.name'], ),
    sa.ForeignKeyConstraint(['following_handle'], ['handle.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow_state')
    op.drop_table('content')
    op.drop_table('handle')
    op.drop_table('user')
    op.drop_table('object')
    # ### end Alembic commands ###
